services:
  encrypt:
    container_name: tariq-encrypt
    networks:
      tariq-net:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - 853:853
      - 4443:4443
    volumes:
      - ${cert}:/ssl/cert.pem
      - ${key}:/ssl/key.pem

networks:
  tariq-net: 
    external: true
